Team/urls.py
# clubs urls.py
from django.conf.urls import patterns, include, url
from Team import views


# TODO: I want to standardize namespace names to all lowercase
# e.g. confirmAskJoin > confirmaskjoin,
#      editMember > editMember
# TODO: addMembers is plural. singularize it
# were we really going to add members en masse?


urlpatterns = [
    url(
        regex=r"^$",
        view=views.TeamListView.as_view(),
        name="list"
    ),
    url(
        regex=r"^new$",
        view=views.TeamCreateView.as_view(),
        name="new"
    ),
    url(
        regex=r"^(?P<pk>\d+)$",
        view=views.TeamDetailView.as_view(),
        name="detail"
    ),
    url(
        regex=r"^join/(?P<pk>\d+)$",
        view=views.TeamAskJoinView.as_view(),
        name="askjoin"
    ),
    url(
        regex=r"^confirm/(?P<pk>\d+)$",
        view=views.TeamConfirmAskJoinView.as_view(),
        name="confirmAskJoin"
    ),
    url(
        regex=r"^deleterequest/(?P<pk>\d+)$",
        view=views.DeletePlayerRequest, 
        name="deleterequest"
        ),
    url(
        regex=r"^deleteplayer/(?P<team>\d+)/(?P<player>\d+)$",
        view=views.DeleteTeamPlayer, 
        name="deleteplayer"
    ),

   url(
        regex=r"^addplayer/(?P<pk>\d+)$",
        view=views.TeamAddPlayerView.as_view(),
        name="addplayer"
    ),

    # url(
    #     regex=r"^removeplayer/(?P<pk>\d+)$",
    #     view=views.TeamRemovePlayerView.as_view(),
    #     name="removeplayer"
    # ),
   # url(
   #      regex=r"^editmember/(?P<pk>\d+)$",
   #      view=views.ClubEditMemberView.as_view(),
   #      name="editMember"
   #  ),
    url(
        regex=r"^results/(?P<pk>\d+)$",
        view=views.TeamResultsView.as_view(),
        name="result"
    ),
    # url(
    #     regex=r"^update/(?P<pk>\d+)$",
    #     view=views.ClubUpdateView.as_view(),
    #     name="update"
    # ),
    # url(
    #     regex=r"^delete/(?P<pk>\d+)$",
    #     view=views.ClubDeleteView.as_view(),
    #     name="delete"
    # ),
]

mysite/urls.py
from django.conf.urls import patterns, include, url

# from . import views
from login.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', welcome),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', logout_page),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
                       url(r'^register/$', register),
                       url(r'^register/success/$', register_success),
                       url(r'^home/$', home),
                       url(r'^locations/', include('locations.urls', namespace='locations')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^search/$', search),
                       url(r'^itinerary/', include('Team.urls', namespace='Team')),



                       )
                       

Team/forms/player_form.py
from django.forms import ModelForm

from Team.models import Team, PlayerRequest

from django.http import Http404
import datetime



# class PlayerRequest(models.Model):
#     requester = models.ForeignKey(User)
#     teamToJoin = models.ForeignKey(Team)
#     # request_date = models.DateField(default=timezone.now)
    # reasonMessage = models.CharField(max_length=200, help_text="Why do you want to join this club?")


class newPlayerForm(ModelForm):
    class Meta:
        model = PlayerRequest
        fields = ["reasonMessage"]

    _requester = None
    _owner = None
    _teamToJoin = None
    _playerToJoin = None

    def set_requester(self, requester):
        self._requester = requester

    def set_owner(self, requester):
        self._owner = owner

    def set_teamToJoin(self, teamToJoin):
        self._teamToJoin = teamToJoin



    def save(self, *args, **kwargs):
        # if self._policy:
        #     self.instance.policies = self._policy
        # else:
        #     return Http404("something is wrong")

        # self.instance.request_date = datetime.datetime.now()
        self.instance.requester = self._requester
        # playerWanted = Player.objects.get(pk=)
        teamWanted = Team.objects.get(pk=self._teamToJoin)
        self.instance.teamToJoin = teamWanted
        # self.instance.clubToJoin = self._clubToJoin
        resp = super(newPlayerForm, self).save(*args, **kwargs)
        return resp

Team/forms/playerrequestform.py
from django.forms import ModelForm

from Team.models import Team, PlayerRequest
from locations.models import Cities

from django.http import Http404
import datetime



# class PlayerRequest(models.Model):
#     requester = models.ForeignKey(User)
#     teamToJoin = models.ForeignKey(Team)
#     # request_date = models.DateField(default=timezone.now)
    # reasonMessage = models.CharField(max_length=200, help_text="Why do you want to join this club?")


class newPlayerRequest(ModelForm):
    class Meta:
        model = PlayerRequest
        fields = ["teamToJoin"]


    _requester = None
    _owner = None
    _teamToJoin = None
    _player = None

    def set_requester(self, requester):
        self._requester = requester

    def set_owner(self, requester):
        self._owner = owner

    def set_player(self, player):
        self._player = player


    def save(self, *args, **kwargs):
        # if self._policy:
        #     self.instance.policies = self._policy
        # else:
        #     return Http404("something is wrong")

        # self.instance.request_date = datetime.datetime.now()
        self.instance.requester = self._requester
        self.instance.player = Cities.objects.get(pk=self._player)
        # teamWanted = Team.objects.get(pk=self._teamToJoin)
        # self.instance.teamToJoin = teamWanted
        # teamWanted = Team.objects.get(pk=self._teamToJoin)
        # self.instance.teamToJoin = teamWanted
        # self.instance.clubToJoin = self._clubToJoin
        resp = super(newPlayerRequest, self).save(*args, **kwargs)
        return resp

Team/forms/team_forms.py
from django.forms import ModelForm

from Team.models import Team

from django.http import Http404
import datetime


class NewTeamForm(ModelForm):
    # name = models.CharField(max_length=20, help_text='Club name')
    # description = models.CharField(max_length=180, help_text='Club description')
    # zipcode = models.CharField(max_length=5)
    # add_date = models.DateField(default=timezone.now)
    # members = models.ManyToManyField(User)
    # policies = models.ForeignKey('clubPolicies.ClubPolicy')
    class Meta:
        model = Team
        fields = ["name"]

    # _leader = None
    _first_member = None

    # def set_leader(self, current_logged_in_member):
    #     self._leader = current_logged_in_member

    # def set_policy(self, policy):
    #     self._policy = policy

    # def get_policy(self):
    #     if self._policy:
    #         return self
    #     else:
    #         return 0

    def set_owner(self, current_logged_in_member):
        self._first_member = current_logged_in_member

    def save(self, *args, **kwargs):
        # TODO: figure out why two club policies are being created
        #       for each club.
        #       Well, get_form is being called during the GET request
        #       and during the POST request. That's why there are two.
        #       The problem is, Club objects require a related ClubPolicy object.
        # if self._policy:
        # old_policy = self._policy
        # self.instance.policies = self._policy
        # old_policy.delete()
        # else:
        #     return Http404("No policies set")
        self.instance.owner = self._first_member
        # self.instance.add_date = datetime.datetime.now(
        # self.instance.player = Cities.objects.get(pk=sel)
        resp = super(NewTeamForm, self).save(*args, **kwargs)
        return resp

Team/views.py
# clubs/views.py
from Team.models import PlayerRequest
from .models import Team, PlayerRequest
from locations.models import Cities
from django.contrib.auth.models import User

# for I18N
from django.utils.translation import ugettext as _

# TSoD page 98, Class-based views
from django.core.urlresolvers import reverse
# end TSoD
# signals.receiver
from django.db.models import signals

from django.http import Http404, HttpResponseRedirect

from django.views.generic import ListView, DetailView, UpdateView, CreateView, DeleteView
from braces.views import LoginRequiredMixin
from django.contrib import messages

from Team.forms.team_forms import NewTeamForm

from Team.forms.player_form import newPlayerForm
from Team.forms.playerrequestform import newPlayerRequest

# from Team.forms.member_form import newMemberForm
from helpers.navbar_helpers import NavBarMixin
from django.contrib import messages


class TeamActionMixin(object):
    
    fields = ('name')
    
    @property
    def success_msg(self):
        return NotImplemented

    @staticmethod
    def is_member_current_user(self, member):
        """
        Is the current user the member being looked at
        :param self:
        :return:
        """
        pass
        

class TeamListView(NavBarMixin, ListView):
    model = Team
    page_title = _("Itinerary List")


class TeamDetailView(LoginRequiredMixin, TeamActionMixin, NavBarMixin, DetailView):
    model = Team
    page_title = _("Itinerary Detail")

    def get_context_data(self, **kwargs):
        # world+dog context data goes here
        context = super(TeamDetailView, self).get_context_data(**kwargs)
        # self.navBar_context(context)
        # context["page_title"] = _("Club Detail")
        # context["available_thingys"] = self.thingys_available()
        this_team = self.get_object(queryset=None)
        # player = self.get_object(queryset=None)
        player_list = this_team.players.all()
        player_requests = PlayerRequest.objects.filter(teamToJoin=this_team)
        avglat = 0
        avglon = 0
        for p in player_requests:
            avglat += p.player.latitude
            avglon += p.player.longitude
        
        if(len(player_requests) > 0):
            context["playlat"] = player_requests[0].player.latitude
            context["playlon"] = player_requests[0].player.longitude
        else:
            context["playlat"] = None
            context["playlon"] = None

        if(len(player_requests) > 1):
            context["dplaylat"] = player_requests[1].player.latitude
            context["dplaylon"] = player_requests[1].player.longitude
        else:
            context["dplaylat"] = None
            context["dplaylon"] = None
        if(len(player_requests) > 0):
            context["avglat"] = avglat
            context["avglon"] = avglon
            avglat = avglat / len(player_requests)
            avglon = avglon / len(player_requests)
        else:
            context["avglat"] = 37.0902
            context["avglon"] = -95.7129

        context["player_request_count"] = len(player_requests)
        context["player_actual_count"] = len(player_list)
        context["player_list"] = player_list
        context["player_request_list"] = player_requests


        return context


# class TeamAndPolicyCreateView(LoginRequiredMixin, TeamActionMixin, NavBarMixin):
#     form_classes = {
#         'newteam': NewTeamForm,
#         'newpolicy': NewTeamPolicyForm,
#     }
#     # the 'templates/' part of the path is implied
#     template_name = 'Team/team_and_policy_form.html'



class TeamCreateView(LoginRequiredMixin, TeamActionMixin, NavBarMixin, CreateView):
    model = Team
    success_msg = _("Itinerary created")
    fields = None
    form_class = NewTeamForm
    page_title = _("Itinerary Create")

    def get_form(self, **kwargs):
        form = super(TeamCreateView, self).get_form(**kwargs)
        form.set_owner(self.request.user)
        # form.set_leader(self.request.user)
        # form.set_policy(Queue.objects.create(public=True, leader=self.request.user))
        # form.set_owner(self.request.user)
        # print("pk of policy object is " + str(NewTeamForm.get_policy))
        return form

    def post(self, request, *args, **kwargs):
        # self.object = None
        return super(CreateView, self).post(request, *args, **kwargs)

    def get_success_url(self):
        return reverse("Team:detail", kwargs={"pk": self.object.pk})

    def form_valid(self, form):
        print("the passed-in 'self' object is a : " + repr(type(self)))
        print("the passed-in 'form' object is a : " + repr(type(form)))
        resp = super(TeamActionMixin, self).form_valid(form)
        # self.object.players.add(self.request.user)
        messages.info(self.request, self.success_msg)
        return resp

    # def get_context_data(self, **kwargs):
    #     # world+dog context data goes here
    #     context = super(ClubDetailView, self).get_context_data(**kwargs)
    #     self.navBar_context(context)
    #     context["page_title"] = _("Club Detail")
    #     # context["available_thingys"] = self.thingys_available()
    #     return context



class TeamResultsView(LoginRequiredMixin, TeamActionMixin, NavBarMixin, DetailView):
    """
    Detail view after create/update of club.
    """
    model = Team
    page_title = _("Itinerary Results")


class TeamUpdateView(LoginRequiredMixin, TeamActionMixin, NavBarMixin, UpdateView):
    model = Team
    success_msg = _("Itinerary updated")
    page_title = _("Itinerary Update")

    def get_success_url(self):
        return reverse("Team:detail", kwargs={"pk": self.object.pk})


class TeamDeleteView(LoginRequiredMixin, TeamActionMixin, DeleteView):
    model = Team
    page_title = _("Itinerary Delete")

    def get_object(self, queryset=None):
        """Hook to ensure club leader guy is request.user"""
        obj = super(TeamDeleteView, self).get_object()
        # leaderGuy = obj.policies.owner
        if not leaderGuy == self.request.user:
            raise Http404(_("You're not the owner of this team, so fuck off."))
        return obj
        
    def get_success_url(self):
        return reverse("Team:list")

###############################################################################
# Club Member stuff

class PlayerActionMixin(object):

    # fields = ('reasonMessage',)

    @property
    def success_msg(self):
        return NotImplemented

    def form_valid(self, form):
        print("the passed-in 'self' object is a : " + repr(type(self)))
        print("the passed-in 'form' object is a : " + repr(type(form)))
        resp = super(PlayerActionMixin, self).form_valid(form)
        # self.object.members.add(self.request.user)
        messages.info(self.request, self.success_msg)
        return resp



# class ClubAddMemberView(LoginRequiredMixin, ClubMemberActionMixin, NavBarMixin, DetailView):
#     """
#     Page where authorized user (leader?) can add members.
#     This may be unnedded, or something like "ClubInviteMembersView".
#     Maybe this is the results page for a member add to a club?
#     """
#     model = MemberRequest
#     page_title = _("Club Add Member")
#     success_msg= _("Member added to club")


#     # TODO: Anyone can approve the member join. They just need to know the url pattern.

#     def get(self, request, pk=None, *args, **kwargs):
#         if pk:
#             member_request_object = MemberRequest.objects.get(pk=pk)
#             askingMember = member_request_object.requester
#             clubToJoin = member_request_object.clubToJoin
#             clubToJoin.add_member(askingMember)
#             member_request_object.delete()

class TeamAddPlayerView(LoginRequiredMixin, PlayerActionMixin, NavBarMixin, DetailView):
    """
    Page where authorized user (leader?) can add members.
    This may be unnedded, or something like "ClubInviteMembersView".
    Maybe this is the results page for a member add to a club?
    """
    model = PlayerRequest
    page_title = _("Itinerary add City")
    success_msg= _("City added to Itinerary")


    # TODO: Anyone can approve the member join. They just need to know the url pattern.

    def get(self, request, pk=None, *args, **kwargs):
        if pk:
            # PlayerRequest.objects.filter(pk=pk)
            player_request_object = PlayerRequest.objects.get(pk=pk)
            # askingPlayer = player_request_object.requester
            teamToJoin = player_request_object.teamToJoin
            player = Player.objects.get(pk=player_request_object.player.pk)
            teamToJoin.add_player(player)
            player_request_object.delete()
            return HttpResponseRedirect(reverse('Team:detail', kwargs={"pk": teamToJoin.pk}))

# class TeamAddPlayerView(LoginRequiredMixin, PlayerActionMixin, NavBarMixin, DetailView):
#     """
#     Page where authorized user (leader?) can add members.
#     This may be unnedded, or something like "ClubInviteMembersView".
#     Maybe this is the results page for a member add to a club?
#     """
#     model = PlayerRequest
#     page_title = _("Club Add Member")
#     success_msg= _("Member added to club")



#     def get(self, request, pk=None, *args, **kwargs):
#         # if pk:
#             player_request = PlayerRequest.objects.get(pk=pk)
#             teamToJoin = player_request.teamToJoin
#             askingUser = self.request.user
            
#             player_requests = PlayerRequest.objects.filter(teamToJoin=this_team)

#             teamToJoin.add_player(player_request.player)

#             player_request_object.delete()
#             return HttpResponseRedirect(reverse('Team:detail', kwargs={"pk": teamToJoin.pk}))
            # else:
            #     return HttpResponseRedirect(redirect_to=reverse('welcome'))

def DeletePlayerRequest(request, pk):
    req = PlayerRequest.objects.get(pk=pk)
    team = req.teamToJoin.pk
    req.delete()

templates/Team/pending_team_list_partial.html
<!-- <ul style="list-style: none;">
    {%  for req in member_requests %}
        <li><a href="{% url 'members:detail' pk=req.requester.pk %}">{{ req.requester.username }}</a> wants to join your club. </li>
        <li>Message: "{{ req.reasonMessage }}"</li>
        {% if leader %}
        <li><a href="{% url 'clubs:addmember' pk=req.pk %}" class="btn btn-lg btn-primary btn-block" >Accept</a></li>
        <li><a href="{% url 'clubs:declinemember' pk=req.pk %}" class="btn btn-lg btn-danger btn-block">Decline</a></li>
        {% elif member %}
        <li>Let your club leader know what you think</li>

        {% else %}
        You shouldn't be seeing this info, since you're not in the club
        {% endif %}
    {% endfor %}
</ul>
 -->

templates/Team/playerrequest_detail.html
{% extends "base.html" %} -->

<div class="container">
    <div class="row">
    {% block title %}Welcome Back{% endblock %}
    {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %}
    {% block content %}
    <div class="col-md-4"></div>
    <div class="container col-md-4">
        <h3>Success!</h3>
        You have added "{{ object.player.city }}",
        to the Itinerary named "{{ object.teamToJoin.name }}"
        for user "{{ object.requester.username }}".
          <!-- <input href="Team:confirmAskJoin" type="submit" value="Save" /> -->

      </div>
            <div class="col-md-4"></div>

    {% endblock %}
    </div>
 </div>

templates/Team/playerrequest_form.html
{% extends "base.html" %} -->

<div class="container">
    <div class="row">
    {% block title %}Welcome Back{% endblock %}
    {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %}
    {% block content %}
    <div class="col-md-4"></div>
    <div class="container col-md-4">
        <h3>Add this City to which Itinerary?</h3>
        
        <form action="" class="form" method="POST">
          {% csrf_token %}
          <ul>
            {{ form.as_ul }}
          </ul>
          <input id="save_team" type="submit" value="Save" />
        </form>
      </div>
            <div class="col-md-4"></div>

    {% endblock %}
    </div>
 </div>

templates/Team/team_and_policy_form.html
{% extends base_leftSidebar.html %}
This is the form for creating club and club policy.

templates/Team/team_detail.html
{% extends "base.html" %}
{% block content %}
<!-- <div class="col-md-2"></div> -->
<div class="container col-md-4">

    <h5><b>Itinerary name: </b>{{ team.name }}</h5>
    <h5><b>Itinerary owner: </b> {{ team.owner }}</h5>
    {{ object.player.name }}


<h5>{{ player_request_count }} Locations in Itinerary for this Template</h5>
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Zipcode  &nbsp;</b> </td>
    <td <b>City  &nbsp;</b></td>
    <td <b>State  &nbsp;</b></td>
    <td <b>County  &nbsp;</b> </td>
    <td <b>Latitude  &nbsp;</b></td>
    <td <b>Longitude  &nbsp;</b> </td>
  </tr>


{% for p in player_request_list %}
  <tr>
    <td>{{ p.player.postalcode }}</td>
    <td>{{ p.player.city }}</td>
    <td>{{ p.player.state }}</td>
    <td>{{ p.player.county }}</td>
    <td>{{ p.player.latitude }}</td>
    <td>{{ p.player.longitude }}</td>
    <td><center><a href="{% url 'Team:deleterequest' p.pk %}" class="btn btn-primary btn-block">Remove from Itinerary</a></center><td>
  </tr>

{%  endfor %}

<!DOCTYPE html>
 <html>
   <head>
     <title>Google Maps JavaScript API v3 Example: Map Simple</title>
     <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
     <meta charset="utf-8">
     <style>
       html, body, #map-canvas {
         margin: 0;
         padding: 0;
         height: 100%;
       }
       #map-canvas {
         width: 500px; 
         height: 300px;
       }
     </style>

<script type="text/javascript" 
               src="http://maps.google.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">
var directionsDisplay;
var directionsService = new google.maps.DirectionsService();
var map;

var locations = [
    // ['Bondi Beach', -33.890542, 151.274856, 4],
    // ['Coogee Beach', -33.923036, 151.259052, 5],
    // ['Cronulla Beach', -34.028249, 151.157507, 3],
    // ['Manly Beach', -33.80010128657071, 151.28747820854187, 2],
    // ['Maroubra Beach', -33.950198, 151.259302, 1]
    {% for p in player_request_list %}
        ['{{ p.player.city }}', {{ p.player.latitude }}, {{ p.player.longitude }}],
    {%  endfor %}
];


var infowindow = new google.maps.InfoWindow();

var marker, i;
function initialize() {
map = new google.maps.Map(document.getElementById('map-canvas'), {
    zoom: 3,
    center: new google.maps.LatLng({{ avglat }}, {{ avglon }}),
    mapTypeId: google.maps.MapTypeId.ROADMAP
});

for (i = 0; i < locations.length; i++) {
    marker = new google.maps.Marker({
        position: new google.maps.LatLng(locations[i][1], locations[i][2]),
        map: map
    });

    google.maps.event.addListener(marker, 'click', (function (marker, i) {
        return function () {
            infowindow.setContent(locations[i][0]);
            infowindow.open(map, marker);
        }
    })(marker, i));
}

directionsDisplay = new google.maps.DirectionsRenderer();

directionsDisplay.setMap(map);

var start = new google.maps.LatLng({{ playlat }}, {{ playlon }});
var end = new google.maps.LatLng({{ dplaylat }}, {{ dplaylon }});
var request = {
    origin: start,
    destination: end,
    travelMode: google.maps.DirectionsTravelMode.DRIVING
};
directionsService.route(request, function (response, status) {
    if (status == google.maps.DirectionsStatus.OK) {
        directionsDisplay.setDirections(response);
    }
});
}
google.maps.event.addDomListener(window, 'load', initialize);
</script>
</head>
<body>
<div id="map-canvas"></div>
</body>
</html>


<!-- <!DOCTYPE html>
    <html> 
    <head> 
       <meta http-equiv="content-type" content="text/html; charset=UTF-8"/> 
       <title>Google Maps API v3 Directions Example</title> 
       <script type="text/javascript" 
               src="http://maps.google.com/maps/api/js?sensor=false"></script>
    </head> 
    <body style="font-family: Arial; font-size: 12px;"> 
       <div style="width: 600px;">
         <div id="map" style="width: 280px; height: 400px; float: left;"></div> 
         <div id="panel" style="width: 300px; float: right;"></div> 
       </div>
       
       <script type="text/javascript"> 
    
         var directionsService = new google.maps.DirectionsService();
         var directionsDisplay = new google.maps.DirectionsRenderer();
    
         var map = new google.maps.Map(document.getElementById('map'), {
           zoom:7,
           mapTypeId: google.maps.MapTypeId.ROADMAP
         });
        
         directionsDisplay.setMap(map);
         // directionsDisplay.setPanel(document.getElementById('panel'));
    
         var request = {
           origin: 'Linkwood', 
           destination: 'Boston',
           travelMode: google.maps.DirectionsTravelMode.DRIVING
         };
    
         directionsService.route(request, function(response, status) {
           if (status == google.maps.DirectionsStatus.OK) {
             directionsDisplay.setDirections(response);
           }
         });
       </script> 
    </body> 
    </html> -->


<!-- <script type="text/javascript" src="http://maps.googleapis.com/maps/api/js?sensor=false"></script>
<script type="text/javascript">




    var markers = [
    {% for p in player_request_list %}

    {
        "title": '{{ p.player.city }}',
        "lat": '{{ p.player.latitude }}',
        "lng": '{{ p.player.longitude }}',
        "description": '{{ p.player.county }}'
    },
    {%  endfor %}

    ];

    // "map" is an instance of GMap3



    window.onload = function () {
        LoadMap();
        initMap();
    }
    function LoadMap() {
        var mapOptions = {
            center: new google.maps.LatLng({{ avglat }}, {{ avglon }}),
            zoom: 2,
            mapTypeId: google.maps.MapTypeId.ROADMAP
        };
        var map = new google.maps.Map(document.getElementById("dvMap"), mapOptions);
 
        //Create and open InfoWindow.
        var infoWindow = new google.maps.InfoWindow();
 
        for (var i = 0; i < markers.length; i++) {
            var data = markers[i];
            var myLatlng = new google.maps.LatLng(data.lat, data.lng);
            var marker = new google.maps.Marker({
                position: myLatlng,
                map: map,
                title: data.title
            });
 
            //Attach click event to the marker.
            (function (marker, data) {
                google.maps.event.addListener(marker, "click", function (e) {
                    //Wrap the content inside an HTML DIV in order to set height and width of InfoWindow.
                    infoWindow.setContent("<div style = 'width:200px;min-height:40px'>" + data.description + "</div>");
                    infoWindow.open(map, marker);
                });
            })(marker, data);
        }
    }
function initMap() {
  var directionsService = new google.maps.DirectionsService;
  var directionsDisplay = new google.maps.DirectionsRenderer;
  var map = new google.maps.Map(document.getElementById('map'), {
    zoom: 7,
    center: {lat: 41.85, lng: -87.65}
  });
  directionsDisplay.setMap(map);

  var onChangeHandler = function() {
    calculateAndDisplayRoute(directionsService, directionsDisplay);
  };
  document.getElementById('start').addEventListener('change', onChangeHandler);
  document.getElementById('end').addEventListener('change', onChangeHandler);
}

function calculateAndDisplayRoute(directionsService, directionsDisplay) {
  directionsService.route({
    origin: document.getElementById('start').value,
    destination: document.getElementById('end').value,
    travelMode: google.maps.TravelMode.DRIVING
  }, function(response, status) {
    if (status === google.maps.DirectionsStatus.OK) {
      directionsDisplay.setDirections(response);
    } else {
      window.alert('Directions request failed due to ' + status);
    }
  });
}    

</script>
<div id="dvMap" style="width: 300px; height: 400px">
</div> -->



{% endblock %}

    

templates/Team/team_form.html
{% extends "base.html" %} -->

<div class="container">
    <div class="row">
    {% block title %}Welcome Back{% endblock %}
    {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %}
    {% block content %}
    <div class="col-md-4"></div>
    <div class="container col-md-4">
        <h3>This is the Team data entry form</h3>
        
        <form action="" class="form" method="POST">
          {% csrf_token %}
          <ul>
            {{ form.as_ul }}
          </ul>
          <input id="save_team" type="submit" value="Save" />
        </form>
      </div>
            <div class="col-md-4"></div>

    {% endblock %}
    </div>
 </div>

templates/Team/team_list.html
{% extends "base_leftSidebar.html" %}
{% block content %}
    {% for team in object_list %}
        <div class="col-sm-4 col-lg-4 col-md-4">
            <!-- <div class="thumbnail"> -->
                <h4><a href="{% url 'Team:detail' team.pk %}">{{ team.name }}</a></h4>
        </div>
    {% endfor %}
{% endblock %}
{% block sidebar %}
{#    TODO: make this look better, think up more content to put here. #}
    List of Itineraries:<br/>
<a href="{% url 'Team:new' %}">Create your own Itinerary</a>
{% endblock %}