Team/urls.py
# clubs urls.py
from django.conf.urls import patterns, include, url
from Team import views


# TODO: I want to standardize namespace names to all lowercase
# e.g. confirmAskJoin > confirmaskjoin,
#      editMember > editMember
# TODO: addMembers is plural. singularize it
# were we really going to add members en masse?


urlpatterns = [
    url(
        regex=r"^$",
        view=views.TeamListView.as_view(),
        name="list"
    ),
    url(
        regex=r"^new$",
        view=views.TeamCreateView.as_view(),
        name="new"
    ),
    url(
        regex=r"^(?P<pk>\d+)$",
        view=views.TeamDetailView.as_view(),
        name="detail"
    ),
    url(
        regex=r"^join/(?P<pk>\d+)$",
        view=views.TeamAskJoinView.as_view(),
        name="askjoin"
    ),
    url(
        regex=r"^confirm/(?P<pk>\d+)$",
        view=views.TeamConfirmAskJoinView.as_view(),
        name="confirmAskJoin"
    ),
    url(
        regex=r"^deleterequest/(?P<pk>\d+)$",
        view=views.DeletePlayerRequest, 
        name="deleterequest"
        ),
    url(
        regex=r"^deleteplayer/(?P<team>\d+)/(?P<player>\d+)$",
        view=views.DeleteTeamPlayer, 
        name="deleteplayer"
    ),

   url(
        regex=r"^addplayer/(?P<pk>\d+)$",
        view=views.TeamAddPlayerView.as_view(),
        name="addplayer"
    ),

    # url(
    #     regex=r"^removeplayer/(?P<pk>\d+)$",
    #     view=views.TeamRemovePlayerView.as_view(),
    #     name="removeplayer"
    # ),
   # url(
   #      regex=r"^editmember/(?P<pk>\d+)$",
   #      view=views.ClubEditMemberView.as_view(),
   #      name="editMember"
   #  ),
    url(
        regex=r"^results/(?P<pk>\d+)$",
        view=views.TeamResultsView.as_view(),
        name="result"
    ),
    # url(
    #     regex=r"^update/(?P<pk>\d+)$",
    #     view=views.ClubUpdateView.as_view(),
    #     name="update"
    # ),
    # url(
    #     regex=r"^delete/(?P<pk>\d+)$",
    #     view=views.ClubDeleteView.as_view(),
    #     name="delete"
    # ),
]

mysite/urls.py
from django.conf.urls import patterns, include, url

# from . import views
from login.views import *

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
                       url(r'^$', welcome),
                       url(r'^login/$', 'django.contrib.auth.views.login', name="login"),
                       url(r'^logout/$', logout_page),
                       url(r'^accounts/login/$', 'django.contrib.auth.views.login'), # If user is not login it will redirect to login page
                       url(r'^register/$', register),
                       url(r'^register/success/$', register_success),
                       url(r'^home/$', home),
                       url(r'^locations/', include('locations.urls', namespace='locations')),
                       url(r'^admin/', include(admin.site.urls)),
                       url(r'^search/$', search),
                       url(r'^itinerary/', include('Team.urls', namespace='Team')),



                       )
                       

templates/cities/cities_detail.html
{% extends "base.html" %}
        <!-- {% block title %}Welcome Back{% endblock %} -->
        <!-- {% block head %}Welcome, {{ user.first_name|upper }}{% endblock %} -->
        {% block content %}
            <div class="col-md-2"></div>
            <div class="container col-md-4">
            <h3>Cities Detail View</h3>
<div class="container col-md-4">
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Zipcode  &nbsp;</b> </td>
    <td <b>City  &nbsp;</b></td>
    <td <b>State  &nbsp;</b></td>
    <td <b>County  &nbsp;</b> </td>
    <td <b>Latitude  &nbsp;</b></td>
    <td <b>Longitude  &nbsp;</b> </td>
  </tr>
{%  for cities in object_list %}
  <tr>
    <td>{{ cities.postalcode }}</td>
    <td>{{ cities.city }}</td>
    <td>{{ cities.state }}</td>
    <td>{{ cities.county }}</td>
    <td>{{ cities.latitude }}</td>
    <td>{{ cities.longitude }}</td>
  </tr>
{% endfor %}
</table> 
</div>
</div>
<br>
</br>
<!DOCTYPE html>
<html>
<head>
<script
src="http://maps.googleapis.com/maps/api/js">
</script>

<script>
var myCenter=new google.maps.LatLng({{ lat }},{{ lon }});

function initialize()
{
var mapProp = {
  center:myCenter,
  zoom:5,
  mapTypeId:google.maps.MapTypeId.ROADMAP
  };

var map=new google.maps.Map(document.getElementById("googleMap"),mapProp);

var marker=new google.maps.Marker({
  position:myCenter,
  });

marker.setMap(map);
}

google.maps.event.addDomListener(window, 'load', initialize);
</script>
</head>

<body>
<div id="googleMap" style="width:500px;height:380px;"></div>
</body>
</html>

<div class="col-md-5"></div>

<!-- <div class="col-md-4"></div> -->
<!-- <div class="col-md-4"> -->
</div>
<!-- <div class="col-md-4"></div> -->



{% endblock %}
        </div>
        <div class="col-md-4"></div>

templates/cities/cities_partial_list.html
{% extends "base.html" %}
{% block content %}

<!-- <div class="col-md-3"></div> -->
<div class="container col-md-4">
<table width="100%" border="1" cellspacing="5" cellpadding="5">  
  <tr>
    <td <b>Zipcode  &nbsp;</b> </td>
    <td <b>City  &nbsp;</b></td>
    <td <b>State  &nbsp;</b></td>
    <td <b>County  &nbsp;</b> </td>
    <td <b>Latitude  &nbsp;</b></td>
    <td <b>Longitude  &nbsp;</b> </td>
  </tr>
{%  for cities in object_list %}
  <tr>
    <td>{{ cities.postalcode }}</td>
    <td> <a href="{% url 'locations:detail' cities.pk %}" style="white-space:nowrap;">{{ cities.city }} &nbsp; </a></td>
    <td>{{ cities.state }}</td>
    <td>{{ cities.county }}</td>
    <td>{{ cities.latitude }}</td>
    <td>{{ cities.longitude }}</td>
  </tr>
{% endfor %}
</table> 
</div>
</div>

{% endblock %}